name: CI Pipeline

on:
  push:
    branches:
      - danque # TODO: switch to main when merging
  pull_request:
    branches:
      - danque # TODO: switch to main when merging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Tests
        run: |
          echo "No tests available yet"
