name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Set AWS Region
        run: |
          export AWS_DEFAULT_REGION=us-west-2
          export AWS_REGION=us-west-2

      # TODO: uncomment this & get UTs to mock AWS properly
      #- name: Run Configuration Service Lambda Tests
      #  run: |
      #    pytest configuration-service/test_configuration_service.py

      #- name: Run Ingestion Service Lambda Tests
      #  run: |
      #    pytest ingestion-service/test_ingestion_service.py
