name: CI Pipeline

on:
  push:
    branches:
      - danque # TODO: switch to main when merging
  pull_request:
    branches:
      - danque # TODO: switch to main when merging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Set AWS Region
        run: |
          export AWS_DEFAULT_REGION=us-west-2
          export AWS_REGION=us-west-2

          # TODO: uncomment this & get UTs to mock AWS properly
      # - name: Run Configuration Service Lambda Tests
      #   run: |
      #     cd configuration-service
      #     python3 -W ignore::DeprecationWarning -m unittest test_config.py

      - name: Run Ingestion Service Lambda Tests
        run: |
          cd ingestion-service
          source ../venv/bin/activate
          python3 -W ignore::DeprecationWarning -m unittest test_ingestion.py

      - name: Run Transformation Service Lambda Tests
        run: |
          cd transformation-service
          python3 -W ignore::DeprecationWarning -m unittest test_transform.py

      - name: Run Delivery Service Lambda Tests
        run: |
          cd delivery-service
          python3 -W ignore::DeprecationWarning -m unittest test_delivery.py
